name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  firebase_crashlytics: ^3.4.19
  firebase_storage: ^11.6.9
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.0
  stream_chat: ^6.10.0
  stream_chat_flutter: ^6.0.0
  stream_chat_flutter_core: ^6.11.0
  stream_chat_persistence: ^6.10.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
