name: flutter_firebase
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.9
  cloud_functions: ^4.6.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_crashlytics: ^3.4.19
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  get_it: ^7.6.7
  go_router: ^13.2.1
  photo_manager: ^3.0.0
  stream_chat: ^7.1.0
  stream_chat_flutter: ^7.1.0
  stream_chat_flutter_core: ^7.1.0
  stream_chat_persistence: ^7.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
