// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRRlfBFtJuq7iGlVW4-VTx0wCeLtV0QFY',
    appId: '1:145475320075:web:68df0691a588ba8fee8a0e',
    messagingSenderId: '145475320075',
    projectId: 'flutter-23679',
    authDomain: 'flutter-23679.firebaseapp.com',
    storageBucket: 'flutter-23679.appspot.com',
    measurementId: 'G-X5CYCX97CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRhjXaUxLfajZV0fgkDkrBWmMDFXAiys4',
    appId: '1:145475320075:android:9e8fc82e29693ff5ee8a0e',
    messagingSenderId: '145475320075',
    projectId: 'flutter-23679',
    storageBucket: 'flutter-23679.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPQmiNrVV8AW5j5btT3s3-8LA4PXwIOQI',
    appId: '1:145475320075:ios:d4adb2005b8e7679ee8a0e',
    messagingSenderId: '145475320075',
    projectId: 'flutter-23679',
    storageBucket: 'flutter-23679.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPQmiNrVV8AW5j5btT3s3-8LA4PXwIOQI',
    appId: '1:145475320075:ios:f88a8d6032f5ccd8ee8a0e',
    messagingSenderId: '145475320075',
    projectId: 'flutter-23679',
    storageBucket: 'flutter-23679.appspot.com',
    iosBundleId: 'com.example.flutterFirebase.RunnerTests',
  );
}
